/*                    
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ethan
 */
public class Interface_Lights_Off extends javax.swing.JFrame {
    GrilleDeJeu grille;
    int nbCoups;
     /* Creates new form Interface_Lights_Off
     */
    public int demanderTailleGrille() {
    // Options disponibles
    String[] options = {"(5x5)", "(7x7)", "(9x9)"};
    
    // Boîte de dialogue pour demander la taille
    int choix = JOptionPane.showOptionDialog(
            this, // Parent Component
            "Choisissez la taille de la grille :", // Message
            "Taille de la Grille", // Titre
            JOptionPane.DEFAULT_OPTION, // Type d'options
            JOptionPane.QUESTION_MESSAGE, // Icône
            null, // Icône personnalisée (null = icône par défaut)
            options, // Options
            options[1] // Option par défaut
    );

    // Renvoie la taille en fonction du choix
    switch (choix) {
        case 0:
            return 5; // Petite grille
        case 1:
            return 7; // Moyenne grille
        case 2:
            return 9; // Grande grille
        default:
            return 7; // Valeur par défaut si aucune sélection
    }
}
    public Interface_Lights_Off() {
        initComponents();
        int n = demanderTailleGrille();
        int nbLignes= n;
        int nbColonnes=n;
        jPanel1.setLayout(new java.awt.GridLayout(nbLignes, 1)); // Ajuste le layout des boutons de lignes
        jPanel4.setLayout(new java.awt.GridLayout(1, nbColonnes));
        this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
        this.nbCoups = 0;
        jPanel2.setLayout(new java.awt.GridLayout(n, n));
       
        // Ajouter les boutons pour les colonnes
        for (int i = 0; i < nbColonnes; i++) {
            JButton button = new JButton("" + i);
            jPanel4.add(button);

            final int colonne = i; // capture de la colonne correspondante
            button.addActionListener(evt -> {
                grille.activerColonneDeCellules(colonne);
                nbCoups++;
                rafraichirGrille();
                verifierConditionVictoire();
            });
        }

        // Ajouter les boutons pour les lignes
        for (int j = 0; j < nbLignes; j++) {
            JButton button = new JButton("" + j);
            jPanel1.add(button);

            final int ligne = j; // capture de la ligne correspondante
            button.addActionListener(evt -> {
                grille.activerLigneDeCellules(ligne);
                nbCoups++;
                rafraichirGrille();
                verifierConditionVictoire();
            });
        }

        // Ajouter les cellules graphiques
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
            int tailleBouton = 600 / n; // Ajuster en fonction de l'espace disponible
            CelluleGraphique button = new CelluleGraphique(grille.matriceCellules[i][j], tailleBouton, tailleBouton);                
            jPanel2.add(button);
            }
        }
        initialiserPartie();
        this.setSize(new java.awt.Dimension(800, 800)); // Ajuster la taille totale si nécessaire
    }
   
    /**
     * Initialise la partie.
     */
    public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
        nbCoups = 0;
        rafraichirGrille();
    }

    /**
     * Met à jour l'affichage graphique des cellules.
     */
    public void rafraichirGrille() {
        jPanel2.repaint();
    }

    /**
    * Vérifie si la condition de victoire est remplie.
    */
    public void verifierConditionVictoire() {
    if (grille.cellulesToutesEteintes()) {
        int choix = JOptionPane.showConfirmDialog(this,
                "Bravo, vous avez gagné en " + nbCoups + " coups !\nVoulez-vous rejouer ?",
                "Victoire",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);

        if (choix == JOptionPane.YES_OPTION) {
            initialiserPartie(); // Réinitialise le jeu
        } else {
            System.exit(0); // Quitte le programme
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new java.awt.GridLayout(1, 7));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(7, 1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(7, 7));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Diagonale Montante ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Diagonale Descendante ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        grille.activerDiagonaleDescendante();
        repaint();
        nbCoups++;
        rafraichirGrille();
        verifierConditionVictoire();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        grille.activerDiagonaleMontante();
        repaint();
        nbCoups++;
        rafraichirGrille();
        verifierConditionVictoire();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Lights_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Lights_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Lights_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Lights_Off.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Lights_Off().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
